CREATE TYPE "public"."gender" AS ENUM('male', 'female');--> statement-breakpoint
CREATE TABLE "customer_owners" (
	"customer_id" integer NOT NULL,
	"belongs_to" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_customer" UNIQUE("customer_id")
);
--> statement-breakpoint
CREATE TABLE "customer_topics" (
	"custom_id" integer NOT NULL,
	"topic_id" varchar(100) NOT NULL,
	"accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customerType" varchar(100) NOT NULL,
	"avatar" text,
	"name" varchar(100) NOT NULL,
	"gender" "gender" NOT NULL,
	"age" integer NOT NULL,
	"position" varchar(100),
	"phone" varchar(20) NOT NULL,
	"email" varchar(255),
	"wechat" varchar(50),
	"company_name" varchar(200) NOT NULL,
	"industry" varchar(100) NOT NULL,
	"scale" varchar(50) NOT NULL,
	"province" varchar(50) NOT NULL,
	"detail_address" text NOT NULL,
	"remarks" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "customer_owners_customer_id_idx" ON "customer_owners" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "customer_owners_owner_id_idx" ON "customer_owners" USING btree ("belongs_to");--> statement-breakpoint
CREATE INDEX "customer_topics_customer_id_idx" ON "customer_topics" USING btree ("custom_id");--> statement-breakpoint
CREATE INDEX "customer_topics_topic_id_idx" ON "customer_topics" USING btree ("topic_id");