CREATE TABLE "agent_suggestions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_suggestions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"suggestion" jsonb NOT NULL,
	"topic_id" text NOT NULL,
	"parent_message_id" text NOT NULL,
	"accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DROP INDEX "customer_sessions_customer_id_idx";--> statement-breakpoint
CREATE INDEX "agent_suggestions_topic_id_idx" ON "agent_suggestions" USING btree ("topic_id");--> statement-breakpoint
CREATE INDEX "agent_suggestions_created_at_idx" ON "agent_suggestions" USING btree ("created_at");--> statement-breakpoint
ALTER TABLE "customer_sessions" DROP COLUMN "customer_id";